#!/usr/bin/env bash
if which patatt>/dev/null 2>&1; then
    # We have it in path, so just execute it
    patatt -q sign --hook "${1}"
else
    # Assume we're symlinked into a git checkout
    REAL_SCRIPT=$(realpath -e ${BASH_SOURCE[0]})
    SCRIPT_TOP="${SCRIPT_TOP:-$(dirname ${REAL_SCRIPT})}"
    PATATT_TOP=$(realpath -e ${SCRIPT_TOP})
    exec env PYTHONPATH="${PATATT_TOP}" python3 "${PATATT_TOP}/patatt/__init__.py" sign --hook "${1}"
fi
